version: "3"
services:
  server2:
    volumes: 
      - '.:/Users/dylan/Documents/College/CSY5/ScalableComputing/FileServer/Servers/Server2'
    # replace username/repo:tag with your name and image details
    build: .
    deploy:
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
    ports:
      - "3000:80"
  